spring.datasource.url=jdbc:postgresql://localhost:5432/mymenu_db
spring.datasource.username=mymenu_user
spring.datasource.password=mymenu_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
groq.api.key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama3-70b-8192