spring.datasource.url=jdbc:postgresql://172.25.224.1:5432/mymenu?sslmode=prefer
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.defer-datasource-initialization=true

# spring.sql.init.data-locations=classpath:database_seed.sql
# spring.sql.init.mode=always

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

server.port=8080