spring.application.name=demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url={YOUR JDBC URL}&password={YOUR SUPABASE DB PASSWORD}
spring.datasource.username={Your DB User Name From Supabase}
spring.datasource.password={Your DB Password From Supabase}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl