-- Script SQL completo para popular o banco com receitas e ingredientes
-- PostgreSQL Database Seed Script

-- Inserting Ingredientes (Ingredients)
INSERT INTO ingrediente (nome) VALUES ('Frango');
INSERT INTO ingrediente (nome) VALUES ('Carne Vermelha');
INSERT INTO ingrediente (nome) VALUES ('Peixe');
INSERT INTO ingrediente (nome) VALUES ('Atum');
INSERT INTO ingrediente (nome) VALUES ('Salmão');
INSERT INTO ingrediente (nome) VALUES ('Tilápia');
INSERT INTO ingrediente (nome) VALUES ('Ovo');
INSERT INTO ingrediente (nome) VALUES ('Leite');
INSERT INTO ingrediente (nome) VALUES ('Queijo Meia Cura');
INSERT INTO ingrediente (nome) VALUES ('Queijo Branco');
INSERT INTO ingrediente (nome) VALUES ('Iogurte');
INSERT INTO ingrediente (nome) VALUES ('Manteiga');
INSERT INTO ingrediente (nome) VALUES ('Azeite');
INSERT INTO ingrediente (nome) VALUES ('Óleo de Canola');
INSERT INTO ingrediente (nome) VALUES ('Aveia');
INSERT INTO ingrediente (nome) VALUES ('Trigo Integral');
INSERT INTO ingrediente (nome) VALUES ('Arroz Integral');
INSERT INTO ingrediente (nome) VALUES ('Batata Doce');
INSERT INTO ingrediente (nome) VALUES ('Batata Inglesa');
INSERT INTO ingrediente (nome) VALUES ('Cebola');
INSERT INTO ingrediente (nome) VALUES ('Alho');
INSERT INTO ingrediente (nome) VALUES ('Tomate');
INSERT INTO ingrediente (nome) VALUES ('Alface');
INSERT INTO ingrediente (nome) VALUES ('Couve');
INSERT INTO ingrediente (nome) VALUES ('Brócolis');
INSERT INTO ingrediente (nome) VALUES ('Cenoura');
INSERT INTO ingrediente (nome) VALUES ('Abobrinha');
INSERT INTO ingrediente (nome) VALUES ('Abóbora');
INSERT INTO ingrediente (nome) VALUES ('Berinjela');
INSERT INTO ingrediente (nome) VALUES ('Chuchu');
INSERT INTO ingrediente (nome) VALUES ('Beterraba');
INSERT INTO ingrediente (nome) VALUES ('Espinafre');
INSERT INTO ingrediente (nome) VALUES ('Banana');
INSERT INTO ingrediente (nome) VALUES ('Maçã');
INSERT INTO ingrediente (nome) VALUES ('Morango');
INSERT INTO ingrediente (nome) VALUES ('Maracujá');
INSERT INTO ingrediente (nome) VALUES ('Laranja');
INSERT INTO ingrediente (nome) VALUES ('Limão');
INSERT INTO ingrediente (nome) VALUES ('Mel');
INSERT INTO ingrediente (nome) VALUES ('Açúcar');
INSERT INTO ingrediente (nome) VALUES ('Sal');
INSERT INTO ingrediente (nome) VALUES ('Pimenta');
INSERT INTO ingrediente (nome) VALUES ('Alecrim');
INSERT INTO ingrediente (nome) VALUES ('Orégano');
INSERT INTO ingrediente (nome) VALUES ('Gengibre');
INSERT INTO ingrediente (nome) VALUES ('Curry');
INSERT INTO ingrediente (nome) VALUES ('Páprica');
INSERT INTO ingrediente (nome) VALUES ('Cúrcuma');
INSERT INTO ingrediente (nome) VALUES ('Cominho');
INSERT INTO ingrediente (nome) VALUES ('Mostarda');
INSERT INTO ingrediente (nome) VALUES ('Molho de Soja');
INSERT INTO ingrediente (nome) VALUES ('Vinagre');
INSERT INTO ingrediente (nome) VALUES ('Limão Siciliano');
INSERT INTO ingrediente (nome) VALUES ('Alho Poró');
INSERT INTO ingrediente (nome) VALUES ('Cebola Roxa');
INSERT INTO ingrediente (nome) VALUES ('Pimentão Verde');
INSERT INTO ingrediente (nome) VALUES ('Pimentão Vermelho');
INSERT INTO ingrediente (nome) VALUES ('Pimentão Amarelo');
INSERT INTO ingrediente (nome) VALUES ('Milho');
INSERT INTO ingrediente (nome) VALUES ('Ervilha');
INSERT INTO ingrediente (nome) VALUES ('Feijão Preto');
INSERT INTO ingrediente (nome) VALUES ('Feijão Carioca');
INSERT INTO ingrediente (nome) VALUES ('Lentilha');
INSERT INTO ingrediente (nome) VALUES ('Grão-de-Bico');
INSERT INTO ingrediente (nome) VALUES ('Macarrão');
INSERT INTO ingrediente (nome) VALUES ('Pão Integral');
INSERT INTO ingrediente (nome) VALUES ('Arroz Branco');
INSERT INTO ingrediente (nome) VALUES ('Quinoa');
INSERT INTO ingrediente (nome) VALUES ('Gergelim');
INSERT INTO ingrediente (nome) VALUES ('Chia');
INSERT INTO ingrediente (nome) VALUES ('Linhaça');
INSERT INTO ingrediente (nome) VALUES ('Pasta de Amendoim');
INSERT INTO ingrediente (nome) VALUES ('Amêndoa');
INSERT INTO ingrediente (nome) VALUES ('Castanha de Caju');
INSERT INTO ingrediente (nome) VALUES ('Noz');
INSERT INTO ingrediente (nome) VALUES ('Cacau em Pó');
INSERT INTO ingrediente (nome) VALUES ('Chocolate 70%');
INSERT INTO ingrediente (nome) VALUES ('Ricota');
INSERT INTO ingrediente (nome) VALUES ('Requeijão Light');
INSERT INTO ingrediente (nome) VALUES ('Cream Cheese');
INSERT INTO ingrediente (nome) VALUES ('Feta');
INSERT INTO ingrediente (nome) VALUES ('Mozzarella');
INSERT INTO ingrediente (nome) VALUES ('Parmesão');
INSERT INTO ingrediente (nome) VALUES ('Maionese Light');
INSERT INTO ingrediente (nome) VALUES ('Ketchup');
INSERT INTO ingrediente (nome) VALUES ('Barbecue');
INSERT INTO ingrediente (nome) VALUES ('Alcachofra');
INSERT INTO ingrediente (nome) VALUES ('Endívia');
INSERT INTO ingrediente (nome) VALUES ('Rúcula');
INSERT INTO ingrediente (nome) VALUES ('Agrião');
INSERT INTO ingrediente (nome) VALUES ('Goiaba');
INSERT INTO ingrediente (nome) VALUES ('Melancia');
INSERT INTO ingrediente (nome) VALUES ('Melão');
INSERT INTO ingrediente (nome) VALUES ('Abacaxi');
INSERT INTO ingrediente (nome) VALUES ('Kiwi');
INSERT INTO ingrediente (nome) VALUES ('Morango');
INSERT INTO ingrediente (nome) VALUES ('Framboesa');
INSERT INTO ingrediente (nome) VALUES ('Amora');
INSERT INTO ingrediente (nome) VALUES ('Mirtilo');
INSERT INTO ingrediente (nome) VALUES ('Uva');
INSERT INTO ingrediente (nome) VALUES ('Manga');
INSERT INTO ingrediente (nome) VALUES ('Abacate');
INSERT INTO ingrediente (nome) VALUES ('Coco Ralado');
INSERT INTO ingrediente (nome) VALUES ('Leite de Coco');
INSERT INTO ingrediente (nome) VALUES ('Água de Coco');
INSERT INTO ingrediente (nome) VALUES ('Fermento em Pó');
INSERT INTO ingrediente (nome) VALUES ('Fermento Biológico');
INSERT INTO ingrediente (nome) VALUES ('Baunilha');
INSERT INTO ingrediente (nome) VALUES ('Canela');
INSERT INTO ingrediente (nome) VALUES ('Noz Moscada');
INSERT INTO ingrediente (nome) VALUES ('Cravo');
INSERT INTO ingrediente (nome) VALUES ('Leite Desnatado');
INSERT INTO ingrediente (nome) VALUES ('Iogurte Grego');

-- Inserting Usuários (Users)
INSERT INTO usuario (id, nome, email, senha, objetivo, dieta_especifica, geladeira_id) VALUES (1, 'Murilo', 'murilo@example.com', '12345', 'Perder peso', 'Vegana', 1);
INSERT INTO usuario (id, nome, email, senha, objetivo, dieta_especifica, geladeira_id) VALUES (2, 'João Silva', 'joao@example.com', '12345', 'Ganhar massa muscular', 'High Protein', 2);
INSERT INTO usuario (id, nome, email, senha, objetivo, dieta_especifica, geladeira_id) VALUES (3, 'Maria Santos', 'maria@example.com', '12345', 'Manter saúde', 'Low Carb', 3);
INSERT INTO usuario (id, nome, email, senha, objetivo, dieta_especifica, geladeira_id) VALUES (4, 'Murilo Vegano', 'murilo.v@example.com', '12345', 'Saúde integral', 'Vegano, Vegetariano', 4);
INSERT INTO usuario (id, nome, email, senha, objetivo, dieta_especifica, geladeira_id) VALUES (5, 'Carlos Vegetariano', 'carlos@example.com', '12345', 'Ganhar massa', 'Vegetariano', 5);

-- Inserting Geladeiras (Fridges)
INSERT INTO geladeira (id) VALUES (1);
INSERT INTO geladeira (id) VALUES (2);
INSERT INTO geladeira (id) VALUES (3);
INSERT INTO geladeira (id) VALUES (4);
INSERT INTO geladeira (id) VALUES (5);

-- Inserting Receitas (Recipes)
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Frango Grelhado com Batata Doce', 'Peito de frango grelhado com batata doce', 25, 'Fácil', 8.0, 'Grelhe o frango temperado e cozinhe a batata doce', 'https://via.placeholder.com/500', 350, 40.0, 45.0, 5.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Salmão Assado com Legumes', 'Salmão fresco com brócolis e cenoura', 30, 'Médio', 25.0, 'Tempere o salmão, asse com os legumes', 'https://via.placeholder.com/500', 420, 35.0, 15.0, 25.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Arroz Integral com Lentilha e Ovos', 'Combinação simples e barata', 35, 'Fácil', 6.0, 'Cozinhe o arroz com a lentilha e sirva com ovos cozidos', 'https://via.placeholder.com/500', 360, 18.0, 55.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Panqueca de Aveia', 'Panqueca rica em fibras e energia', 10, 'Fácil', 4.5, 'Misture aveia, ovo e banana amassada. Doure na frigideira', 'https://via.placeholder.com/500', 250, 12.0, 35.0, 6.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Omelete Simples', 'Omelete rápido de dois ovos', 5, 'Fácil', 2.0, 'Bata os ovos com sal e pimenta. Cozinhe em frigideira untada', 'https://via.placeholder.com/500', 180, 14.0, 2.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Tapioca com Queijo Branco', 'Clássico leve e rápido', 5, 'Fácil', 3.5, 'Peneire a goma na frigideira e recheie com queijo minas', 'https://via.placeholder.com/500', 220, 8.0, 40.0, 4.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Crepioca de Frango', 'Mistura de ovo e tapioca com recheio proteico', 10, 'Fácil', 5.0, 'Bata o ovo com a tapioca. Faça a massa e recheie com frango desfiado', 'https://via.placeholder.com/500', 280, 25.0, 20.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Vitamina de Banana e Mamão', 'Bebida rápida, ótima digestão', 5, 'Fácil', 3.0, 'Bata as frutas com leite desnatado no liquidificador', 'https://via.placeholder.com/500', 150, 6.0, 30.0, 1.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sanduíche Natural de Atum', 'Lanche prático e rico em ômega 3', 10, 'Fácil', 6.0, 'Misture atum com maionese light e coloque no pão integral', 'https://via.placeholder.com/500', 310, 18.0, 35.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Iogurte com Granola e Mel', 'Lanche rápido com bons carboidratos', 2, 'Fácil', 4.0, 'Sirva o iogurte natural coberto com granola e mel', 'https://via.placeholder.com/500', 200, 7.0, 35.0, 4.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Torrada com Pasta de Amendoim', 'Fonte de gorduras boas e energia', 3, 'Fácil', 3.5, 'Espalhe a pasta de amendoim sobre fatias de pão integral tostadas', 'https://via.placeholder.com/500', 250, 9.0, 20.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bolo de Caneca de Chocolate Fit', 'Para matar a vontade de doce rapidamente', 5, 'Fácil', 4.0, 'Misture cacau, aveia, ovo e fermento. Asse no microondas por 2 min', 'https://via.placeholder.com/500', 210, 10.0, 25.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Smoothie Verde', 'Refrescante e detox', 5, 'Fácil', 3.0, 'Bata couve, limão, maçã e gengibre com água gelada', 'https://via.placeholder.com/500', 90, 2.0, 22.0, 0.5);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Macarrão Integral a Bolonhesa', 'Energia duradoura com molho rico', 35, 'Médio', 15.0, 'Cozinhe a massa. Faça o molho com carne moída e tomates frescos', 'https://via.placeholder.com/500', 450, 35.0, 60.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Tilápia Assada com Legumes', 'Refeição muito leve e de fácil digestão', 40, 'Médio', 14.0, 'Tempere a tilápia com limão. Asse junto com brócolis e cenoura', 'https://via.placeholder.com/500', 280, 30.0, 15.0, 7.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Salmão com Crosta de Gergelim', 'Rico em gorduras saudáveis', 20, 'Médio', 25.0, 'Passe o salmão no gergelim e sele na frigideira. Sirva com aspargos', 'https://via.placeholder.com/500', 420, 35.0, 5.0, 25.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Escondidinho de Frango e Batata Doce', 'Confort food em versão fit', 45, 'Difícil', 15.0, 'Faça um purê de batata doce e intercale com frango desfiado. Gratine', 'https://via.placeholder.com/500', 380, 35.0, 40.0, 8.0);

-- Insert 82 more recipes to total 100
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pad Thai Vegano', 'Macarrão Tailandês', 25, 'Médio', 10.0, 'Refogue os ingredientes e passe o macarrão', 'https://via.placeholder.com/500', 320, 8.0, 50.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Curry de Grão-de-Bico', 'Indiano temperado', 30, 'Médio', 12.0, 'Cozinhe a mistura até incorporar os sabores', 'https://via.placeholder.com/500', 280, 12.0, 40.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Tacos de Frango', 'Mexicano clássico', 15, 'Fácil', 8.0, 'Tempere e sirva em tortillas', 'https://via.placeholder.com/500', 350, 25.0, 40.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sushi Caseiro', 'Rolls variados', 60, 'Difícil', 20.0, 'Cozinhe o arroz, prepare os recheios e enrole', 'https://via.placeholder.com/500', 280, 15.0, 45.0, 5.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pizza Integral', 'Com massa integral', 40, 'Médio', 12.0, 'Faça a massa e cubra com ingredientes', 'https://via.placeholder.com/500', 380, 15.0, 50.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Estrogonofe de Cogumelos', 'Vegetariano cremoso', 25, 'Médio', 15.0, 'Refogue e adicione o creme', 'https://via.placeholder.com/500', 320, 10.0, 30.0, 18.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Risoto de Brócolis', 'Italiano', 30, 'Médio', 14.0, 'Vá adicionando caldo e mexa sempre', 'https://via.placeholder.com/500', 360, 12.0, 55.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Torta de Espinafre', 'Vegetariana', 50, 'Médio', 18.0, 'Pré-asse a massa e adicione o recheio', 'https://via.placeholder.com/500', 340, 14.0, 35.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Quesadilla de Queijo', 'Mexicana', 10, 'Fácil', 6.0, 'Recheie e doure na frigideira', 'https://via.placeholder.com/500', 380, 15.0, 40.0, 18.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sopa de Abóbora', 'Vegana e cremosa', 35, 'Fácil', 7.0, 'Cozinhe e bata até atingir consistência', 'https://via.placeholder.com/500', 180, 4.0, 35.0, 2.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Hambúrguer Caseiro', 'Suculento', 20, 'Médio', 12.0, 'Molde e asse ou frite', 'https://via.placeholder.com/500', 420, 28.0, 35.0, 20.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Camarão ao Alho', 'Sofisticado', 15, 'Médio', 22.0, 'Refogue rapidamente', 'https://via.placeholder.com/500', 220, 30.0, 5.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Frango à Parmegiana', 'Clássico Italiano', 45, 'Médio', 16.0, 'Empane, frite e asse com molho', 'https://via.placeholder.com/500', 480, 32.0, 40.0, 22.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Feijoada Leve', 'Tradicional', 90, 'Médio', 10.0, 'Cozinhe lentamente para potencializar sabores', 'https://via.placeholder.com/500', 380, 20.0, 50.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Moqueca de Peixe', 'Bahiana', 35, 'Médio', 18.0, 'Cozinhe em panela fechada', 'https://via.placeholder.com/500', 340, 32.0, 15.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Churrasco Vegano', 'À base de plantas', 40, 'Médio', 14.0, 'Use proteína de soja texturizada', 'https://via.placeholder.com/500', 320, 18.0, 45.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Salada Mediterrânea', 'Fresca e leve', 15, 'Fácil', 12.0, 'Misture bem os ingredientes', 'https://via.placeholder.com/500', 280, 8.0, 25.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Ceviche de Peixe', 'Peruano', 30, 'Médio', 16.0, 'Marine em suco de limão', 'https://via.placeholder.com/500', 200, 28.0, 10.0, 4.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Salada de Frutas', 'Vegana', 15, 'Fácil', 8.0, 'Corte e misture', 'https://via.placeholder.com/500', 150, 2.0, 35.0, 1.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Espaguete à Carbonara Light', 'Italiano', 20, 'Médio', 12.0, 'Use ovos e queijo light', 'https://via.placeholder.com/500', 350, 18.0, 45.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Frittata de Legumes', 'Italiana', 25, 'Fácil', 8.0, 'Cozinhe na panela e termine no forno', 'https://via.placeholder.com/500', 280, 16.0, 20.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bife Acebolado', 'Tradicional', 25, 'Fácil', 14.0, 'Grelhe a carne e refogue a cebola', 'https://via.placeholder.com/500', 380, 35.0, 15.0, 20.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Caldo de Carne', 'Reconfortante', 120, 'Fácil', 10.0, 'Cozinhe lentamente', 'https://via.placeholder.com/500', 220, 25.0, 15.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Frango com Repolho', 'Rápido', 20, 'Fácil', 7.0, 'Refogue rápido para manter a textura', 'https://via.placeholder.com/500', 320, 32.0, 20.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Caldo Verde', 'Português', 30, 'Fácil', 6.0, 'Cozinhe as batatas e adicione couve', 'https://via.placeholder.com/500', 180, 8.0, 35.0, 2.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Brigadeiro Fit', 'Doce', 10, 'Fácil', 5.0, 'Mexa até atingir ponto', 'https://via.placeholder.com/500', 140, 4.0, 20.0, 5.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pudim de Chia', 'Vegano', 5, 'Fácil', 6.0, 'Deixe na geladeira', 'https://via.placeholder.com/500', 160, 5.0, 18.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Granola Caseira', 'Breakfast', 20, 'Fácil', 8.0, 'Asse até ficar crocante', 'https://via.placeholder.com/500', 380, 12.0, 50.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Mingau de Aveia', 'Breakfast', 10, 'Fácil', 3.0, 'Cozinhe em água ou leite', 'https://via.placeholder.com/500', 200, 8.0, 35.0, 4.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Waffle Integral', 'Breakfast', 15, 'Fácil', 6.0, 'Use máquina de waffle', 'https://via.placeholder.com/500', 280, 10.0, 40.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Açaí Bowl', 'Breakfast', 5, 'Fácil', 10.0, 'Bata a polpa com leite', 'https://via.placeholder.com/500', 320, 8.0, 55.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Ovo Poché', 'Breakfast', 5, 'Médio', 3.0, 'Mexa a água e cozinhe delicadamente', 'https://via.placeholder.com/500', 140, 12.0, 1.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Banana com Canela', 'Breakfast', 5, 'Fácil', 2.0, 'Frita ou assada', 'https://via.placeholder.com/500', 120, 1.0, 28.0, 0.5);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sorvete de Banana', 'Vegano', 10, 'Fácil', 4.0, 'Congele e bata', 'https://via.placeholder.com/500', 100, 1.0, 25.0, 0.3);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Mousse de Chocolate', 'Sobremesa', 15, 'Fácil', 8.0, 'Bata e refrigere', 'https://via.placeholder.com/500', 240, 6.0, 30.0, 11.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pavê', 'Sobremesa', 30, 'Médio', 12.0, 'Intercale biscoitos e creme', 'https://via.placeholder.com/500', 320, 4.0, 45.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Torta de Morango', 'Sobremesa', 45, 'Médio', 14.0, 'Asse a massa e cubra com morango', 'https://via.placeholder.com/500', 280, 4.0, 40.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Arroz Doce', 'Sobremesa', 40, 'Fácil', 5.0, 'Cozinhe em leite com canela', 'https://via.placeholder.com/500', 240, 4.0, 50.0, 2.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pudim de Leite Condensado', 'Sobremesa', 20, 'Fácil', 8.0, 'Cozinhe em banho-maria', 'https://via.placeholder.com/500', 320, 5.0, 55.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bolo de Chocolate', 'Sobremesa', 45, 'Médio', 10.0, 'Misture e asse', 'https://via.placeholder.com/500', 380, 6.0, 55.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Biscoito de Polvilho', 'Salgado', 20, 'Fácil', 4.0, 'Frite ou asse', 'https://via.placeholder.com/500', 280, 4.0, 30.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pão Caseiro', 'Salgado', 120, 'Médio', 6.0, 'Fermente e asse', 'https://via.placeholder.com/500', 260, 8.0, 50.0, 2.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bolo Salgado de Milho', 'Salgado', 35, 'Fácil', 7.0, 'Misture e asse', 'https://via.placeholder.com/500', 220, 6.0, 35.0, 6.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bolinhas de Queijo', 'Salgado', 25, 'Fácil', 6.0, 'Forme e frite', 'https://via.placeholder.com/500', 240, 8.0, 25.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pastel de Queijo', 'Salgado', 20, 'Médio', 7.0, 'Recheie e frite', 'https://via.placeholder.com/500', 280, 8.0, 30.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Empada', 'Salgado', 45, 'Médio', 10.0, 'Faça a massa e recheie', 'https://via.placeholder.com/500', 320, 6.0, 35.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sanduíche de Pulled Pork', 'Americano', 120, 'Médio', 18.0, 'Cozinhe lentamente e desfiador', 'https://via.placeholder.com/500', 420, 32.0, 40.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Galinha Caipira', 'Tradicional', 90, 'Médio', 15.0, 'Cozinhe em caldo', 'https://via.placeholder.com/500', 380, 38.0, 8.0, 20.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Coxa e Sobrecoxa Temperada', 'Rápido', 35, 'Fácil', 10.0, 'Asse com ervas', 'https://via.placeholder.com/500', 340, 40.0, 5.0, 18.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Asa de Frango Temperada', 'Rápido', 30, 'Fácil', 8.0, 'Asse ou frite', 'https://via.placeholder.com/500', 280, 35.0, 2.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Almôndegas', 'Italiano', 30, 'Médio', 12.0, 'Molde e asse', 'https://via.placeholder.com/500', 360, 30.0, 25.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bifes à Milanesa', 'Clássico', 20, 'Fácil', 14.0, 'Empane e frite', 'https://via.placeholder.com/500', 420, 32.0, 30.0, 20.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Carne de Sol', 'Nordestina', 20, 'Fácil', 16.0, 'Desfia e refogue', 'https://via.placeholder.com/500', 340, 40.0, 5.0, 18.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Costela Assada', 'Churrascaria', 120, 'Médio', 20.0, 'Asse lentamente', 'https://via.placeholder.com/500', 460, 42.0, 2.0, 32.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Picanha Grelhada', 'Churrasco', 25, 'Fácil', 22.0, 'Grelhe em fogo alto', 'https://via.placeholder.com/500', 480, 45.0, 0.0, 35.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Alcatra Grelhada', 'Churrasco', 20, 'Fácil', 20.0, 'Grelhe rápido', 'https://via.placeholder.com/500', 420, 44.0, 0.0, 26.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Fraldinha Grelhada', 'Churrasco', 15, 'Fácil', 18.0, 'Pouco tempo no fogo', 'https://via.placeholder.com/500', 400, 43.0, 0.0, 24.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Entrecosto Grelhado', 'Churrasco', 20, 'Fácil', 16.0, 'Grelhe em fogo médio', 'https://via.placeholder.com/500', 380, 40.0, 0.0, 23.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Coração Grelhado', 'Churrasco', 10, 'Fácil', 12.0, 'Grelhe bem rápido', 'https://via.placeholder.com/500', 280, 38.0, 0.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Linguado Assado', 'Sofisticado', 20, 'Médio', 20.0, 'Asse inteiro', 'https://via.placeholder.com/500', 220, 32.0, 3.0, 9.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Sardinha Grelhada', 'Rápido', 10, 'Fácil', 8.0, 'Grelhe direto', 'https://via.placeholder.com/500', 280, 32.0, 0.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Truta Assada', 'Sofisticada', 25, 'Médio', 18.0, 'Asse com limão', 'https://via.placeholder.com/500', 300, 35.0, 2.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Bacalau à Brás', 'Tradicional', 45, 'Médio', 16.0, 'Desfie e refogue', 'https://via.placeholder.com/500', 360, 28.0, 35.0, 15.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Polvo à Galega', 'Português', 45, 'Difícil', 24.0, 'Cozinhe macio e temperado', 'https://via.placeholder.com/500', 260, 30.0, 10.0, 10.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Peixe em Escabeche', 'Clássico', 35, 'Médio', 14.0, 'Frite e cubra com molho', 'https://via.placeholder.com/500', 340, 30.0, 20.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Lula à Milanesa', 'Clássico', 25, 'Médio', 16.0, 'Empane e frite', 'https://via.placeholder.com/500', 340, 28.0, 25.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Vieira Grelhada', 'Sofisticado', 10, 'Fácil', 28.0, 'Grelhe bem rápido', 'https://via.placeholder.com/500', 200, 30.0, 5.0, 6.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Ostra', 'Sofisticado', 5, 'Fácil', 30.0, 'Abra e sirva fresca', 'https://via.placeholder.com/500', 150, 18.0, 7.0, 5.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Atum Sellado', 'Sofisticado', 15, 'Médio', 20.0, 'Sele brevemente na panela', 'https://via.placeholder.com/500', 280, 35.0, 2.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Filé de Peixe à Dorê', 'Clássico', 20, 'Fácil', 12.0, 'Empane levemente e frite', 'https://via.placeholder.com/500', 320, 32.0, 15.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Caldo de Peixe', 'Tradicional', 90, 'Fácil', 10.0, 'Cozinhe os espinhos', 'https://via.placeholder.com/500', 180, 20.0, 15.0, 6.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Pataniscas', 'Português', 20, 'Médio', 9.0, 'Empane e frite', 'https://via.placeholder.com/500', 300, 25.0, 20.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Ratatouille', 'Vegano', 45, 'Médio', 12.0, 'Refogue os legumes em camadas', 'https://via.placeholder.com/500', 200, 6.0, 30.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Berinjela à Parmegiana', 'Vegetariana', 50, 'Médio', 14.0, 'Frite e monta em camadas', 'https://via.placeholder.com/500', 340, 12.0, 35.0, 16.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Couve à Mineira', 'Vegetariana', 15, 'Fácil', 5.0, 'Refogue em tiras finas', 'https://via.placeholder.com/500', 180, 6.0, 20.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Abobrinha Refogada', 'Vegetariana', 15, 'Fácil', 4.0, 'Refogue em rodelas', 'https://via.placeholder.com/500', 160, 4.0, 18.0, 8.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Brócolis ao Alho', 'Vegetariana', 15, 'Fácil', 6.0, 'Cozinhe e refogue', 'https://via.placeholder.com/500', 140, 8.0, 15.0, 5.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Batata Doce Assada', 'Vegetariana', 45, 'Fácil', 5.0, 'Asse e sirva simples', 'https://via.placeholder.com/500', 180, 3.0, 40.0, 0.5);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Batata-Doce Frita', 'Vegetariana', 20, 'Fácil', 5.0, 'Corte em palitos e frite', 'https://via.placeholder.com/500', 320, 3.0, 50.0, 12.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Purê de Batata', 'Vegetariana', 25, 'Fácil', 4.0, 'Cozinhe e amasse', 'https://via.placeholder.com/500', 220, 4.0, 42.0, 4.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Purê de Cenoura', 'Vegano', 25, 'Fácil', 3.0, 'Cozinhe e bata', 'https://via.placeholder.com/500', 140, 2.0, 30.0, 1.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Abóbora Assada', 'Vegano', 50, 'Fácil', 4.0, 'Asse até amolecer', 'https://via.placeholder.com/500', 100, 1.5, 22.0, 0.3);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Manteiga de Amendoim Caseira', 'Vegano', 10, 'Fácil', 8.0, 'Bata até vira pasta', 'https://via.placeholder.com/500', 380, 12.0, 10.0, 32.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Leite de Coco Caseiro', 'Vegano', 15, 'Fácil', 6.0, 'Bata coco ralado com água', 'https://via.placeholder.com/500', 320, 3.0, 5.0, 32.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Leite de Amêndoa', 'Vegano', 10, 'Fácil', 8.0, 'Bata amêndoas com água', 'https://via.placeholder.com/500', 180, 6.0, 8.0, 14.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Suco de Laranja Fresco', 'Vegano', 5, 'Fácil', 3.0, 'Esprema as laranjas', 'https://via.placeholder.com/500', 110, 1.0, 25.0, 0.5);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Água com Limão', 'Vegano', 2, 'Fácil', 1.0, 'Esprema o limão na água', 'https://via.placeholder.com/500', 30, 0.0, 8.0, 0.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Chá Verde', 'Vegano', 5, 'Fácil', 2.0, 'Ferva água e deixe repousar', 'https://via.placeholder.com/500', 10, 0.0, 0.0, 0.0);
INSERT INTO receita (nome, descricao, tempo_preparo, nivel_dificuldade, custo_estimado, instrucoes, imagem_url, kcal, proteina, carboidrato, gordura) VALUES ('Café com Leite', 'Simples', 5, 'Fácil', 3.0, 'Misture café coado com leite', 'https://via.placeholder.com/500', 80, 4.0, 8.0, 3.0);

-- Inserting Item Receita (Recipe Items)
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (431, 835, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (431, 852, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (431, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (432, 839, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (432, 859, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (432, 860, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (433, 851, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (433, 841, 2, 'unidades');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (433, 854, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (434, 849, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (434, 867, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (434, 841, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (435, 841, 2, 'unidades');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (435, 846, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (435, 875, 1, 'pitada');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (436, 843, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (436, 879, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (436, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (437, 841, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (437, 879, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (437, 835, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (438, 867, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (438, 868, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (438, 841, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (439, 838, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (439, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (439, 893, 2, 'fatias');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (440, 845, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (440, 881, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (440, 873, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (441, 907, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (441, 893, 2, 'fatias');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (442, 907, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (442, 909, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (442, 841, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (443, 858, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (443, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (443, 872, 1, 'cm de raiz');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (444, 901, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (444, 856, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (444, 854, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (445, 840, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (445, 859, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (445, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (446, 839, 250, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (446, 904, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (446, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (447, 835, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (447, 852, 2, 'unidades');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (447, 847, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (448, 857, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (448, 861, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (448, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (449, 837, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (449, 871, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (449, 872, 1, 'cm de raiz');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (450, 901, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (450, 864, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (450, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (451, 901, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (451, 883, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (452, 909, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (452, 847, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (453, 857, 150, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (453, 854, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (454, 869, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (454, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (455, 836, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (455, 901, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (456, 891, 250, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (456, 854, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (457, 840, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (457, 860, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (458, 861, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (458, 857, 100, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (459, 902, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (459, 844, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (460, 836, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (460, 859, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (461, 891, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (461, 883, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (462, 909, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (462, 847, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (463, 857, 150, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (463, 854, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (464, 869, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (464, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (465, 909, 250, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (465, 877, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (466, 867, 100, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (466, 874, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (467, 909, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (467, 841, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (468, 867, 250, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (468, 879, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (469, 878, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (469, 842, 250, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (470, 868, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (470, 879, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (471, 844, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (471, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (472, 846, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (472, 864, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (473, 843, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (473, 856, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (474, 841, 2, 'unidades');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (474, 859, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (475, 835, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (475, 836, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (476, 839, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (476, 860, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (477, 859, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (477, 860, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (478, 859, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (478, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (479, 840, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (479, 861, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (480, 836, 250, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (480, 895, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (481, 838, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (481, 864, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (482, 835, 500, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (482, 854, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (483, 835, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (483, 860, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (484, 835, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (484, 859, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (485, 835, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (485, 864, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (486, 837, 400, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (486, 860, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (487, 837, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (487, 864, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (488, 840, 250, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (488, 859, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (489, 838, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (489, 864, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (490, 858, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (490, 862, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (491, 863, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (491, 861, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (492, 865, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (492, 859, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (493, 866, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (493, 862, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (494, 867, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (494, 869, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (495, 874, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (495, 876, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (496, 867, 250, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (496, 907, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (497, 871, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (497, 872, 1, 'cm de raiz');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (498, 842, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (498, 867, 100, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (499, 842, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (499, 905, 30, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (500, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (500, 874, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (501, 867, 150, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (501, 854, 50, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (502, 878, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (502, 867, 100, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (503, 877, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (503, 874, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (504, 870, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (505, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (506, 909, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (506, 874, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (507, 893, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (507, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (508, 897, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (508, 867, 100, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (509, 891, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (509, 901, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (510, 852, 1, 'unidade');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (510, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (511, 862, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (511, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (512, 861, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (512, 860, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (513, 860, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (513, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (514, 858, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (514, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (515, 859, 150, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (515, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (516, 852, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (516, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (517, 852, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (517, 848, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (518, 862, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (518, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (519, 853, 300, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (519, 847, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (520, 853, 200, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (520, 846, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (521, 854, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (521, 883, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (522, 899, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (522, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (523, 872, 2, 'cm de raiz');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (523, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (524, 870, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (524, 842, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (525, 905, 40, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (525, 867, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (526, 906, 40, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (526, 867, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (527, 869, 100, 'g');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (527, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (528, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (528, 876, 2, 'colheres de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (529, 871, 1, 'colher de sopa');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (529, 872, 1, 'cm de raiz');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (530, 867, 200, 'ml');
INSERT INTO item_receita (receita_id, ingrediente_id, quantidade, unidade_medida) VALUES (530, 871, 1, 'colher de sopa');

-- Reset sequences to ensure no conflicts with future inserts
SELECT setval('ingrediente_id_seq', 947, false);
SELECT setval('receita_id_seq', 531, false);
SELECT setval('usuario_id_seq', 6, false);
SELECT setval('geladeira_id_seq', 6, false);
SELECT setval('item_receita_id_seq', 201, false);
SELECT setval('lista_de_compras_id_seq', 1, false);
SELECT setval('item_lista_compras_id_seq', 1, false);
SELECT setval('cardapio_semanal_id_seq', 1, false);
SELECT setval('item_cardapio_id_seq', 1, false);
SELECT setval('item_geladeira_id_seq', 1, false);
